name: CI Pipeline

on:
  push:
    branches:
      - main

# Ensure only one workflow per branch runs, cancel older ones
concurrency:
  group: ci-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    # Run only if this workflow is for the latest commit
    if: ${{ github.event.head_commit.id == github.sha }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          npm install
          sleep 60   # simulate long-running step

      - name: Run Tests
        run: |
          npm test
          sleep 60   # simulate long-running step







          
